### ISSUE TITLE
pyqreg fails to build in Python 3.11 under windows

### ISSUE THREAD

**Issue by mvds314** [mozjay0619/pyqreg#30]
pyqreg fails to build under Python 3.11 (Windows, particularly, I am using Winpython 3.11.1.0)

>     blas_lapack.c
>       src/pyqreg/c\blas_lapack.c(198): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
>       error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
>       [end of output]

I believe this is related to some changes in Python 3.11:
[https://docs.python.org/3/whatsnew/3.11.html](https://docs.python.org/3/whatsnew/3.11.html)

> The non-limited API files cellobject.h, classobject.h, code.h, context.h, funcobject.h, genobject.h and longintrepr.h have been moved to the Include/cpython directory. Moreover, the eval.h header file was removed. These files must not be included directly, as they are already included in Python.h: [Include Files](https://docs.python.org/3/c-api/intro.html#api-includes). If they have been included directly, consider including Python.h instead.

**Comment by mvds314** [comment]
I believe I figured out what causes the problem above in Python 3.11. I believe Python 3.10 has the same problem.
I'm not that familiar with compiled C code and connecting it to Python. But, if I'm correct, cython generates the *.c files automatically right?

Now, if clone your repo, and throw away the *.c files in the c folder, everything works fine (tested with Python 3.11 under Linux), i.e., I can just `pip install -e .` the local repo. What I believe is causing problems, is that, apparently, some of the header files required by the c code are organized differently in Python 3.11 (see the link in the post above). The c files include in repo, were probably generated under Python 3.9, and they no longer work under Python 3.11.

Did you include the *.c files in the repo for the no_cython option in your setup.py? If so, you need to set up some logic that uses other .c files for higher versions of Python. Alternatively, you can just remove the c files, and just make cython a mandatory requirement for installation.

**Comment by mozjay0619** [comment]
Yes, you are right, thanks for the solution. Glad you were able to find the work around. Let me look into including multiple .c version files. If not, I will make it mandatory to build .c files (at least for python>=3.10). Thanks!

**Comment by mvds314** [comment]
I'm still using your code. I created a PR to make it compatible with newer versions of Python:
https://github.com/mozjay0619/pyqreg/pull/33
Is this something you could and want to integrate?
