### PR TITLE
Compatibility newer versions of Python

### LINKED ISSUE #30: pyqreg fails to build in Python 3.11 under windows
pyqreg fails to build under Python 3.11 (Windows, particularly, I am using Winpython 3.11.1.0)

>     blas_lapack.c
>       src/pyqreg/c\blas_lapack.c(198): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
>       error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
>       [end of output]

I believe this is related to some changes in Python 3.11:
[https://docs.python.org/3/whatsnew/3.11.html](https://docs.python.org/3/whatsnew/3.11.html)

> The non-limited API files cellobject.h, classobject.h, code.h, context.h, funcobject.h, genobject.h and longintrepr.h have been moved to the Include/cpython directory. Moreover, the eval.h header file was removed. These files must not be included directly, as they are already included in Python.h: [Include Files](https://docs.python.org/3/c-api/intro.html#api-includes). If they have been included directly, consider including Python.h instead.

### PR DESCRIPTION
**Pull request by mvds314**
@mozjay0619 I am still using your code and created a PR to fix some things so that it keeps working with newer Python versions. Would this be something you could and are willing to incorporate?

Improvements:

- Compatibility with numpy >2 (https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword)
- Switch to pyproject.toml
- Remove c files from the repo for compatibility newer Python versions

Fixes #30 #32

### CODE REVIEW

**Comment by mvds314** [comment]
Hi @mozjay0619, thanks for writing pyqreg. It has been genuinely useful.

Since this PR has been open for a while, I have published the changes as a fork on PyPI so that people hitting the same compatibility problems have something they can install today. It is available as `pyqreg2`, but the import name is unchanged, so it works as a drop-in replacement:

    pip install pyqreg2

    import pyqreg  # unchanged

Source: https://github.com/mvds314/pyqreg  |  PyPI: https://pypi.org/project/pyqreg2/

It adds support for Python 3.11-3.13 and NumPy 2.x, and ships prebuilt wheels for Linux, macOS and Windows, so users no longer need a compiler and the Cython toolchain to install. It keeps your BSD 3-Clause license and all credit for the implementation is yours.

This PR is not withdrawn. I am very happy to see these changes land upstream instead, and would gladly rebase or adjust it if you would like to merge it. The fork exists only so users are not stuck in the meantime, not to compete with this project.
